before_script: psql -c 'create database rpush_test;' -U postgres >/dev/null
language: ruby
install: tools/cached-bundle install --deployment
services:
- redis-server
matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.1.3
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: 2.0.0
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.1.3
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.0.0
    gemfile: Gemfile.rails-3
    env: CLIENT=redis
  - rvm: 2.1.3
    gemfile: Gemfile.rails-3
    env: CLIENT=redis
  - rvm: 2.0.0
    gemfile: Gemfile.rails-3
    env: CLIENT=active_record
  - rvm: 2.1.3
    gemfile: Gemfile.rails-3
    env: CLIENT=active_record
  - rvm: rbx-2.2.10
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: rbx-2.2.10
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: jruby-1.7.16
    gemfile: Gemfile
    env: CLIENT=active_record
  - rvm: jruby-1.7.16
    gemfile: Gemfile
    env: CLIENT=redis
  - rvm: 2.2.0-preview1
    gemfile: Gemfile
    env: CLIENT=active_record
  allow_failures:
  - rvm: 2.2.0-preview1

env:
  global:
    - AMAZON_S3_BUCKET=rpush
    - AMAZON_ACCESS_KEY_ID=AKIAIWENGKCRZZX7NGOQ
    - secure: "JZSnurdpqClRgy2s99xFaOymuCDaCh8rZmHgj8Wj/KRFNDuEFVq7CgUjAg24shL4aB+uE/sgBemfsuvJLcWT27/7bi1h/idepNdB36l+GhdJj5CovtqPGX9rXv6vp1s0tELgjxTcx17IQ1oZ5iqTozg9UWWpCXtOBB70/aJvTn8="
