before_script: "psql -c 'create database rapns_test;' -U postgres >/dev/null"
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode
gemfile:
  - Gemfile
  - Gemfile.rails-4.0

matrix:
  exclude:
    - rvm: ree
      gemfile: Gemfile.rails-4.0
    - rvm: jruby-18mode
      gemfile: Gemfile.rails-4.0
    - rvm: jruby-19mode
      gemfile: Gemfile.rails-4.0
    - rvm: rbx-19mode
      gemfile: Gemfile.rails-4.0
