language: ruby

dist: xenial

cache: bundler

compiler: clang

rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4

# Build only commits on master for the "Build pushed branches" feature. This
# prevents building twice on PRs originating from our repo ("Build pushed pull
# requests)". See:
#   - https://github.com/travis-ci/travis-ci/issues/1147
#   - https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
branches:
  only:
    - master

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

services:
  - postgresql
  - redis-server

before_script: psql -c 'create database rpush_test;' -U postgres >/dev/null
before_install:
  # https://github.com/rubygems/rubygems/issues/3036
  # https://github.com/rubygems/rubygems/issues/3036#issuecomment-566132226
  - yes | gem update --system
  # Rails 4.2 doesn't support bundler 2.0, so we need to lock bundler to
  # v1.17.3. This is just for Ruby 2.5 which ships with bundler 2.x on Travis
  # CI while Ruby 2.6 does not.
  - yes | rvm @global do gem install bundler -v 1.17.3 || true

env:
  matrix:
    - CLIENT=active_record
    - CLIENT=redis

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/rails_4.2.gemfile
      rvm: 2.5.6
  exclude:
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.4.7

jobs:
  include:
    - stage: Lint
      rvm: 2.6.4
      script: bundle exec rake rubocop
