language: ruby

dist: xenial

cache: bundler

compiler: clang

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

# Build only commits on master for the "Build pushed branches" feature. This
# prevents building twice on PRs originating from our repo ("Build pushed pull
# requests)". See:
#   - https://github.com/travis-ci/travis-ci/issues/1147
#   - https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
branches:
  only:
    - master

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

services:
  - postgresql
  - redis-server

before_script: psql -c 'create database rpush_test;' -U postgres >/dev/null
before_install:
  - gem install rubygems-update && update_rubygems
  # Rails 4.2 doesn't support bundler 2.0, so we have multiple workarounds.
  # This is just for Rails 2.5 which ships with bundler 2.x on Travis CI while
  # Ruby 2.6 does not. Taken from:
  # https://github.com/travis-ci/travis-ci/issues/8717#issuecomment-366500378
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  # This should help with the other Ruby versions.
  # Taken from https://docs.travis-ci.com/user/languages/ruby/
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

env:
  matrix:
    - CLIENT=active_record
    - CLIENT=redis

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.6.0
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.5.3
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.6.0
    - gemfile: gemfiles/rails_5.2.gemfile
      env: CLIENT=redis
  exclude:
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.4.5
